### ISSUE TITLE
Clarify if secret gists work

### ISSUE THREAD

**Issue by ghost** [exuanbo/actions-deploy-gist#87]
https://github.com/exuanbo/actions-deploy-gist#prep-work says that I have to create a public gist.

However, I'd like to deploy my private repository to a private gist.

Is this possible with this action?

**Comment by thadk** [comment]
Yes, I was able to test this with a secret gist. Keep in mind you use the id from the URL, but not the URL itself.

**Comment by exuanbo** [comment]
Yes it works on both public and private gist. I have updated README for clarification.
