### ISSUE TITLE
`description` parameter

### ISSUE THREAD

**Issue by eggplants** [exuanbo/actions-deploy-gist#88]
Please add `description` parameter.

Ref: https://docs.github.com/en/rest/reference/gists#update-a-gist

Thank you for your great work.

**Comment by exuanbo** [comment]
Thanks for your suggestion. `gist_description` is added in `v1.1.0` and `v1`.

**Comment by eggplants** [comment]
Thank you so much!

**Comment by eggplants** [comment]
Thanks to this action, I was able to complete my workflow!

https://github.com/eggplants/laughing-broccoli/blob/master/.github/workflows/year.yml

Deployment:
https://gist.github.com/eggplants/b6a25f05a48b086ee73592d3f9d965d6
